#!/usr/bin/env python
#-*- Mode:Python -*-
import os, sys
from core import JEntry, JIndex

def main(argv = None):
    if argv is None:
        argv = sys.argv
    if len(argv) == 1:
        print "Usage: %s [target]" %  argv[0]
        return 1
    if(len(argv) > 2):
        # Special index/tag handling
        jpage = JIndex(argv[1], argv[2:])
    else:
        jpage = JEntry(os.path.join(os.getcwd(), 'in', argv[1] + '.txt'))
    jpage.publish()

if __name__ == "__main__":
    main()
# vim:set shiftwidth=4 softtabstop=4 expandtab:
