#!/usr/bin/env python
#-*- Mode:Python -*-
import os, sys
from core import JEntry

def main(argv = None):
    if argv is None:
        argv = sys.argv
    if len(argv) == 1:
        print "Usage: %s [target]" %  argv[0]
        return 1
    jentry = JEntry(os.path.join(os.getcwd(), 'in', argv[1] + '.txt'))
    jentry.publish()

if __name__ == "__main__":
    main()
